version: 1

formatters:
    prettyFormatter:
        format: '%(asctime)s [%(levelname)8s] --- %(message)s (%(filename)s:%(lineno)s)'
        datefmt: '%Y/%m/%d %H:%M:%S'
loggers:
    vra_rest:
        level: DEBUG
        handlers: [stderr]
        propagate: false
handlers:
    console:
        class: logging.StreamHandler
        formatter: prettyFormatter
        level: DEBUG
        stream: ext://sys.stdout
    stderr:
        class: logging.StreamHandler
        formatter: prettyFormatter
        level: DEBUG
        stream: ext://sys.stderr
root:
    level: DEBUG
    handlers: [console]
